src/Entity/Marketplace.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\MarketplaceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MarketplaceRepository::class)
 */
class Marketplace
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $working_time;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="marketplaces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getWorkingTime(): ?string
    {
        return $this->working_time;
    }

    public function setWorkingTime(string $working_time): self
    {
        $this->working_time = $working_time;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/MarketplaceType.php
<?php

namespace App\Form;

use App\Entity\Marketplace;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MarketplaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('adress')
            ->add('working_time')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Marketplace::class,
        ]);
    }
}

src/Controller/MarketplaceController.php
<?php

namespace App\Controller;

use App\Entity\Marketplace;
use App\Form\MarketplaceType;
use App\Repository\MarketplaceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/marketplace")
 */
class MarketplaceController extends AbstractController
{
    /**
     * @Route("/", name="marketplace_index", methods={"GET"})
     */
    public function index(MarketplaceRepository $marketplaceRepository): Response
    {
        if(sizeof($this->getUser()->getRoles())==2){
            $markets=$marketplaceRepository->findAll();
            }else{
                $markets=$marketplaceRepository->findBy(['user' => $this->getUser()]);
            }
        return $this->render('marketplace/index.html.twig', [
            'marketplaces' => $markets,
        ]);
    }

    /**
     * @Route("/new", name="marketplace_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $marketplace = new Marketplace();
        $form = $this->createForm(MarketplaceType::class, $marketplace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $marketplace->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($marketplace);
            $entityManager->flush();

            return $this->redirectToRoute('marketplace_index');
        }

        return $this->render('marketplace/new.html.twig', [
            'marketplace' => $marketplace,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="marketplace_show", methods={"GET"})
     */
    public function show(Marketplace $marketplace): Response
    {
        return $this->render('marketplace/show.html.twig', [
            'marketplace' => $marketplace,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="marketplace_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Marketplace $marketplace): Response
    {
        $form = $this->createForm(MarketplaceType::class, $marketplace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('marketplace_index');
        }

        return $this->render('marketplace/edit.html.twig', [
            'marketplace' => $marketplace,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="marketplace_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Marketplace $marketplace): Response
    {
        if ($this->isCsrfTokenValid('delete'.$marketplace->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($marketplace);
            $entityManager->flush();
        }

        return $this->redirectToRoute('marketplace_index');
    }
}

templates/marketplace/_delete_form.html.twig
<form method="post" action="{{ path('marketplace_delete', {'id': marketplace.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ marketplace.id) }}">
    <button class="btn">Delete</button>
</form>

templates/marketplace/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/marketplace/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Marketplace{% endblock %}

{% block body %}
    <h1>Edit Marketplace</h1>

    {{ include('marketplace/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('marketplace_index') }}">back to list</a>

    {{ include('marketplace/_delete_form.html.twig') }}
{% endblock %}

templates/marketplace/index.html.twig
{% extends 'none.html.twig' %}

{% block title %}Marketplace index{% endblock %}

{% block body %}

<div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">Marketplace Index</h2>
                <a href="{{ path('marketplace_new') }}"> <button class="au-btn au-btn-icon au-btn--blue">
                                        <i class="zmdi zmdi-plus"></i>Add new Marketplace</button></a>
                                </div>
                            </div>
                        </div>
                        <div class="row m-t-30">
                            <div class="col-md-12">
                                <div   class="table-responsive m-b-40">
                                    <table class="table table-borderless table-striped table-data3">
                                        <thead>
                                            <tr>
                                                <th>Adress</th>
                                                <th>Working Time</th>
                                                <th>Owner</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                                {% for marketplace in marketplaces %}
                                            <tr>
                                                <td>{{ marketplace.adress }}</td>
                                                <td>{{ marketplace.workingTime }}</td>
                                                <td>{{ marketplace.getUser().getName() }}</td>
                                                <td>
                                                    <a href="{{ path('marketplace_show', {'id': marketplace.id}) }}">show</a>
                                                    <a href="{{ path('marketplace_edit', {'id': marketplace.id}) }}">edit</a>
                                                </td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td colspan="12">no records found</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>								
                        </div>						
                    </div>
                </div>
            </div>



{% endblock %}

templates/marketplace/new.html.twig
{% extends 'none.html.twig' %}

{% block title %}New Marketplace{% endblock %}

{% block body %}

<style>
    small{
        color: red;
    }
</style>

            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-header">
                                        <strong>Add a new</strong> MarketPlace
                                    </div>
                                    <div class="card-body card-block">
                             {{ form_start(form, {'attr': {'class': 'login100-form validate-form flex-sb flex-w',novalidate: 'novalidate'}}) }}
                                            <div class="row form-group">
                                                <div class="col col-md-3">
                                                    <label for="text-inpsut" class=" form-control-label">Adress</label>
                                                </div>
                                                <div class="col-12 col-md-9">
                                 {{ form_widget(form.adress, {'attr': {'class': 'form-control','type': 'text'} }) }}		
                                                    <small class="help-block form-text">{{ form_errors(form.adress) }}</small>
                                                </div>
                                            </div>            


                                            <div class="row form-group">
                                                <div class="col col-md-3">
                                                    <label for="text-inpsut" class=" form-control-label">Working Time</label>
                                                </div>
                                                <div class="col-12 col-md-9">
                                 {{ form_widget(form.working_time, {'attr': {'class': 'form-control','type': 'text'} }) }}		
                                                    <small class="help-block form-text">{{ form_errors(form.working_time) }}</small>
                                                </div>
                                            </div>            



                                    </div>
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary btn-sm">
                                            <i class="fa fa-dot-circle-o"></i> Submit
                                        </button>
                                       <a href="{{ path('marketplace_index') }}"> <button type="reset" class="btn btn-danger btn-sm">
                                            <i class="fa fa-ban"></i> Go Back
                                        </button></a>
                                    </div>
                        {{ form_rest(form) }}
                        {{ form_end(form) }}
                                </div>
                            </div>
      
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

templates/marketplace/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Marketplace{% endblock %}

{% block body %}
    <h1>Marketplace</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ marketplace.id }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ marketplace.adress }}</td>
            </tr>
            <tr>
                <th>Working_time</th>
                <td>{{ marketplace.workingTime }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('marketplace_index') }}">back to list</a>

    <a href="{{ path('marketplace_edit', {'id': marketplace.id}) }}">edit</a>

    {{ include('marketplace/_delete_form.html.twig') }}
{% endblock %}